import { useState } from "react";

export default function App() {
  const [analyzed, setAnalyzed] = useState(false);
  const [prCreated, setPrCreated] = useState(false);

  return (
    <div
      style={{
        maxWidth: "900px",
        margin: "40px auto",
        fontFamily: "sans-serif",
        padding: "0 20px",
        color: "#222",
      }}
    >
      <header
        style={{
          borderBottom: "1px solid #eee",
          paddingBottom: "15px",
          marginBottom: "25px",
        }}
      >
        <h1 style={{ fontSize: "28px", margin: 0 }}>
          Bob Debugging Pipeline
        </h1>

        <p style={{ color: "#666", marginTop: "8px" }}>
          AI-powered debugging, testing and GitHub workflow
        </p>

        <p style={{ fontSize: "13px", color: "#888" }}>
          Repo: MBen213/bob-debug-pipeline
        </p>
      </header>

      {/* 1. Bug / Stack Trace Input */}
      <section style={{ marginBottom: "25px" }}>
        <h2 style={{ fontSize: "18px" }}>1. Bug / Stack Trace</h2>

        <textarea
          rows={8}
          style={{
            width: "100%",
            padding: "12px",
            fontFamily: "monospace",
            borderRadius: "6px",
            border: "1px solid #ccc",
            boxSizing: "border-box",
          }}
          defaultValue={`Jest failure:

Expected: null
Received: undefined

File:
tests/userService.test.js

Test:
getUserById(999)`}
        />

        <button
          onClick={() => setAnalyzed(true)}
          style={{
            marginTop: "12px",
            padding: "10px 20px",
            backgroundColor: "#2563eb",
            color: "#fff",
            border: "none",
            borderRadius: "6px",
            cursor: "pointer",
            fontWeight: "bold",
          }}
        >
          Analyze Bug
        </button>
      </section>

      {analyzed && (
        <div style={{ display: "flex", flexDirection: "column", gap: "15px" }}>
          {/* 2. Root Cause */}
          <section
            style={{
              padding: "18px",
              backgroundColor: "#f8fafc",
              border: "1px solid #e2e8f0",
              borderRadius: "8px",
            }}
          >
            <h2 style={{ fontSize: "18px", marginTop: 0 }}>
              2. Root Cause Analysis
            </h2>

            <p>
              <code>Array.find()</code> returns{" "}
              <code>undefined</code> when no user matches the given ID.
            </p>

            <p style={{ marginBottom: 0 }}>
              The test contract requires <code>null</code> when the user does
              not exist.
            </p>
          </section>

          {/* 3. Regression Test */}
          <section
            style={{
              padding: "18px",
              backgroundColor: "#fffbe6",
              border: "1px solid #ffe58f",
              borderRadius: "8px",
            }}
          >
            <h2 style={{ fontSize: "18px", marginTop: 0 }}>
              3. Regression Test
            </h2>

            <p>
              Test case: <code>getUserById(999)</code>
            </p>

            <p style={{ marginBottom: 0 }}>
              Expected: <strong>null</strong>
            </p>
          </section>

          {/* 4. Fix */}
          <section
            style={{
              padding: "18px",
              backgroundColor: "#f0f9ff",
              border: "1px solid #bae6fd",
              borderRadius: "8px",
            }}
          >
            <h2 style={{ fontSize: "18px", marginTop: 0 }}>
              4. Fix Generated by Bob
            </h2>

            <pre
              style={{
                backgroundColor: "#fff",
                padding: "14px",
                borderRadius: "6px",
                overflowX: "auto",
              }}
            >
{`- return users.find(user => user.id === id);
+ return users.find(user => user.id === id) ?? null;`}
            </pre>

            <p style={{ marginBottom: 0 }}>
              File: <code>test-project/src/userService.js</code>
            </p>
          </section>

          {/* 5. Validation */}
          <section
            style={{
              padding: "18px",
              backgroundColor: "#f0fdf4",
              border: "1px solid #bbf7d0",
              borderRadius: "8px",
            }}
          >
            <h2 style={{ fontSize: "18px", marginTop: 0 }}>
              5. Test Validation
            </h2>

            <p
              style={{
                color: "#15803d",
                fontWeight: "bold",
                marginBottom: 0,
              }}
            >
              PASS — tests/userService.test.js
            </p>

            <p style={{ marginBottom: 0 }}>
              2 tests passed
            </p>
          </section>

          {/* 6. GitHub */}
          <section style={{ marginTop: "5px" }}>
            <h2 style={{ fontSize: "18px" }}>6. GitHub Pull Request</h2>

            {!prCreated ? (
              <button
                onClick={() => setPrCreated(true)}
                style={{
                  padding: "12px 24px",
                  backgroundColor: "#16a34a",
                  color: "#fff",
                  border: "none",
                  borderRadius: "6px",
                  fontWeight: "bold",
                  cursor: "pointer",
                  fontSize: "15px",
                }}
              >
                Create GitHub PR
              </button>
            ) : (
              <div
                style={{
                  padding: "15px",
                  backgroundColor: "#f0fdf4",
                  border: "1px solid #bbf7d0",
                  borderRadius: "8px",
                }}
              >
                <p
                  style={{
                    color: "#15803d",
                    fontWeight: "bold",
                    margin: "0 0 8px 0",
                  }}
                >
                  PR workflow triggered
                </p>

                <a
                  href="https://github.com/MBen213/bob-debug-pipeline/pulls"
                  target="_blank"
                  rel="noreferrer"
                  style={{ color: "#2563eb" }}
                >
                  Open GitHub Pull Requests
                </a>
              </div>
            )}
          </section>
        </div>
      )}
    </div>
  );
}